name: Train (daily logistic)
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Days of history for training'
        default: '30'
        required: false
      symbols:
        description: 'Comma separated symbols (default 10)'
        required: false
  schedule:
    - cron: "10 1 * * *"
permissions:
  contents: write
concurrency:
  group: train
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Train models
        env:
          TRAIN_DAYS: ${{ github.event.inputs.days || '30' }}
          SYMBOLS: ${{ github.event.inputs.symbols || 'BTCUSDT,ETHUSDT,XRPUSDT,BNBUSDT,SOLUSDT,DOGEUSDT,ADAUSDT,LTCUSDT,SHIBUSDT,PUMPUSDT' }}
        run: |
          python -V
          python scripts/train.py
      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(models): update logistic weights [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
